name: Docker Image CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 为构建 Docker 镜像设置 Buildx，可以提高构建速度和兼容性
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 自动获取当前日期并作为环境变量
      - name: Set the latest version
        id: get-version
        run: echo "VERSION=latest" >> $GITHUB_ENV

      - name: Set the project name
        id: project-name
        run: echo "PROJECT_NAME=jweboy/jweboy_server" >> $GITHUB_ENV

      - name: Set the host
        id: host
        run: echo "HOST=registry.cn-hangzhou.aliyuncs.com" >> $GITHUB_ENV

        # Docker 登录
      - name: Log in to Alibaba Cloud Docker Registry
        run: |
          echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login --username=1259524459@qq.com ${{env.HOST}} --password-stdin

      # 构建镜像
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.PROJECT_NAME }}:${{ env.VERSION }}

      # 镜像打标
      - name: Tag the Docker image
        run: docker tag ${{ env.PROJECT_NAME }}:${{ env.VERSION }} ${{env.HOST}}/${{ env.PROJECT_NAME }}:${{ env.VERSION }}

      # 推送镜像
      - name: Push the Docker image
        run: docker push ${{env.HOST}}/${{ env.PROJECT_NAME }}:${{ env.VERSION }}
